spring:
  application:
    name: social-media-backend

  datasource:
    url: ${DBMS_CONNECTION:jdbc:postgresql://localhost:5432/social-media}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
      enable_lazy_load_no_trans: true

  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

jwt:
  signerKey: DWZ2Go7aj6GCJkkcF8OS8KmbEQMZpwSvh4RQDlrjwLPU4IhPdENlZH7VOh7g6d8b

server:
  port: 8080
